language: go

go:
    - 1.3

install:
    - go get github.com/jacobsa/ogletest
    - go get github.com/jacobsa/oglematchers
    - go get github.com/smartystreets/goconvey
    - go get github.com/julienschmidt/httprouter
