language: go

go:
    - 1.3

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get code.google.com/p/go.tools/cmd/cover

install:
    - go get github.com/jacobsa/ogletest
    - go get github.com/jacobsa/oglematchers
    - go get github.com/stretchr/testify    
    - go get github.com/julienschmidt/httprouter


script:
      - $HOME/gopath/bin/goveralls -repotoken JAGOu8XbQMyiisbkgvhfw7pf2G6Mir4C9
